### ISSUE TITLE
Not all themes installed

### ISSUE THREAD

**Issue by dkgamer02ai** [Exodia-OS/exodia-bspwm#10]
I just installed Exodia and when I went into the theme selection menu
I saw that many of the themes are missing 
Can you please look into this
![Screenshot_2024-02-27-10-05-18_primary](https://github.com/Exodia-OS/exodia-bspwm/assets/112185917/a42d3fd3-d8df-4ad2-8083-0553a6e3c63b)
I only got these

**Comment by mmsaeed509** [comment]
here are the rest of [themes](https://github.com/Exodia-OS/bspwm-themes)

**Comment by arin-prashar** [comment]
how do I install them ??

**Comment by dkgamer02ai** [comment]
Thank you

**Comment by dkgamer02ai** [comment]
Can Be closed
