### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by k1lgor** [Exodia-OS/exodia-bspwm#4]
Hi guys, 
when upgrading the system, I saw a syntax error while upgrading exodia-bspwm
![image](https://user-images.githubusercontent.com/65338982/206865379-4ff63c72-360f-4a13-bae6-03f295dcde8c.png)
I think is from the empty function `post_remove()` in `exodia-bspwm.install`

**Comment by mmsaeed509** [comment]
I'm gonna check, but it doesn't effect
