### ISSUE TITLE
Dependencies not found, I hvae installed oh-my-posh and jgmenu but still showing missing dependencies

### ISSUE THREAD

**Issue by Sharon218** [Exodia-OS/exodia-bspwm#7]
`ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> exodia-oh-my-posh
  -> exodia-jgmenu
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.`

**Comment by mmsaeed509** [comment]
try reinstalling them again
```bash
install exodia-jgmenu exodia-oh-my-posh
```
