### ISSUE TITLE
can't install updates

### ISSUE THREAD

**Issue by skiss0** [Exodia-OS/exodia-bspwm#8]
I'm on the 11.2022 wireless version, the final part is missing in the photo, because when I press enter the terminal closes

![IMG_20231102_004143](https://github.com/Exodia-OS/exodia-bspwm/assets/39972504/1580e7a0-df1e-4512-b6f6-f5150de9e0d4)

**Comment by skiss0** [comment]
![IMG_20231102_011410](https://github.com/Exodia-OS/exodia-bspwm/assets/39972504/90c3f876-7cbf-4956-850b-13c868031bdd)
![IMG_20231102_011502](https://github.com/Exodia-OS/exodia-bspwm/assets/39972504/0a1e384a-c13a-42de-a8de-4b98c08b8fee)
![IMG_20231102_031216](https://github.com/Exodia-OS/exodia-bspwm/assets/39972504/7a1833e2-1159-4710-b0b9-5b3997cca1e2)

**Comment by mmsaeed509** [comment]
read how to fix [PGP signature Error](https://exodia-os.github.io/wiki/blog/1-PGP-signature)
